Push to origin instead of the URL
Without this change, I'm getting "stale info" error:

    + git push https://***@github.com/wentasah/nix-ros-overlay develop --force-with-lease
    To https://github.com/wentasah/nix-ros-overlay
     ! [rejected]          develop -> develop (stale info)
    error: failed to push some refs to 'https://github.com/wentasah/nix-ros-overlay'

That's probably because when pushing to URL, git doesn't have info
about the URL, it only know about the configured remotes. Therefore,
we change the URL of the origin remote and use "origin" in the push
command.